version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.10.23-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 10s
      timeout: 5s
      retries: 5

  python_publisher:
    container_name: python-publisher-container
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      rabbitmq:
        condition: service_healthy

  spark-master:
    container_name: spark-master-container
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
    volumes:
      - ./output:/opt/bitnami/spark/output
    ports:
      - 8080:8080

  spark-worker:
    container_name: spark-worker-container
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./output:/opt/bitnami/spark/output