---
version: '3.8'

volumes:
    pulsar-data:
        driver: local

services:
    starrock-app:
        image: starrocks/allin1-ubuntu:2.5.6
        container_name: starrock-app
        ports:
            - 8030:8030
            - 8040:8040
            - 8080:8080
            - 9030:9030
        volumes:
            - ./starRocks/jobs:/jobs

    master:
        image: bde2020/spark-master:3.1.1-hadoop3.2
        container_name: spark-master
        ports:
        - 8079:8080
        - 7077:7077
        environment:
        - SPARK_CONF_DIR=/conf
        - SPARK_PUBLIC_DNS=spark-master
        volumes:
        - ./spark/conf/master:/conf
        - ./spark/jobs/:/spark/jobs

    worker:
        image: bde2020/spark-worker:3.1.1-hadoop3.2
        container_name: spark-worker
        depends_on:
        - master
        environment:
        - SPARK_MASTER=spark://spark-master:7077
        volumes:
        - ./spark/conf/worker:/conf
        - ./spark/jobs/:/spark/jobs
        
    rabbitmq:
        image: rabbitmq:management
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      
networks:
  default:
    driver: bridge
